name: Build and deploy

on:
  push:
    branches:
      - 'develop'
      
jobs:
  build:
    runs-on: ubintu-latest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      
      - name: Login DockerHub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Docker Buildx
      - uses: docker/setup-buildx-action@v1
      
      - name: Build and push
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/shipping-service:latest
